export { default as Home } from './Home'
export { default as Films } from './Films'
export { default as People } from './People'
export { default as Planets } from './Planets'
export { default as Species } from './Species'
export { default as Starships } from './Starships'
export { default as Vehicles } from './Vehicles'
